volumes:
  pg_data:
  cache:
  rabbitmq-data:

services:

  backend:
    build: ./app/
    container_name: pomodoro_backend
    command: bash /app/startup.sh
    env_file: .env.containers
    restart: always
    depends_on:
      db:
        condition: service_started
      cache:
        condition: service_started
      rabbitmq:
        condition: service_started

  db:
    image: postgres:15
    container_name: pomodoro_db
    env_file: .env.containers
    volumes:
      - pg_data:/var/lib/postgresql/data

  gateway:
    build: ./nginx/
    container_name: pomodoro_nginx
    env_file: .env.containers
    ports:
      - 8000:80
    depends_on:
      backend:
        condition: service_started

  cache:
    image: redis:7.4.1
    container_name: pomodoro_cache
    command: redis-server
    restart: always
    volumes:
      - cache:/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: pomodoro_rabbitmq
    env_file: .env.containers
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
