"""task_category_relationships

Revision ID: 1fb8556c4436
Revises: 3ff42eb56b18
Create Date: 2024-10-24 20:26:58.507932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fb8556c4436'
down_revision: Union[str, None] = '3ff42eb56b18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_tasks_category_id'), 'tasks', ['category_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_category_id'), table_name='tasks')
    op.drop_column('tasks', 'category_id')
    # ### end Alembic commands ###
