"""tasks_author

Revision ID: e10cf263f2fe
Revises: 0fb3611a1d60
Create Date: 2024-10-27 14:02:27.971606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e10cf263f2fe'
down_revision: Union[str, None] = '0fb3611a1d60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('author_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_tasks_author_id'), 'tasks', ['author_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_author_id'), table_name='tasks')
    op.drop_column('tasks', 'author_id')
    # ### end Alembic commands ###
